name: build

on:
  pull_request: {}
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 11

      # For watchOS x86 simulator. Remove with Kotlin 1.8.
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '13.4.1'

      - run: ./gradlew build assembleAndroidTest dokkaHtmlMultiModule

      - name: Run Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 24
          script: ./gradlew connectedCheck

      - name: Deploy docs to website
        if: ${{ github.ref == 'refs/heads/trunk' }}
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: site
          FOLDER: build/dokka/htmlMultiModule
          TARGET_FOLDER: docs/latest/
          CLEAN: true
