name: build

on:
  pull_request: {}
  workflow_dispatch:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 11

      # For watchOS x86 simulator. Remove with Kotlin 1.8.
      #- uses: maxim-lobanov/setup-xcode@v1
      #  with:
      #    xcode-version: '13.4.1'

      #- run: ./gradlew assemble jvmTest
      - run: ./gradlew :kotunil:build
