name: dokku

on:
  pull_request: {}
  push:
    branches:
      - '**'


env:
  GRADLE_OPTS: "-Dorg.gradle.jvmargs=-Xmx6g -Dorg.gradle.daemon=false -Dkotlin.incremental=false"

jobs:
  publish:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3.10.0
        with:
          distribution: 'zulu'
          java-version: 19

      - name: Build and publish artifacts
        run: ./gradlew dokkaHtmlMultiModule --parallel

      - name: Deploy docs to website
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: site
          FOLDER: build/dokka/htmlMultiModule/
          TARGET_FOLDER: docs/
          CLEAN: true